ARCHITECTURE_VERSION = "SPORTS_NOVA_V3_ARCH_1"
MODEL_VERSION = "sports_nova_v3.drive_block.1"
GRANULARITY = "DRIVE/BLOCK_LEVEL"
TARGET_N_SIMS = 10_000
RESIDUAL_DEPENDENCY = "NONE"
RNG_ALGORITHM = "PCG64DXSM"
